name: "Docker build"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
        type: string

jobs:
  build-push:
    runs-on: gha-runner-scale-set-eks
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: linux/amd64
          tags: ${{ vars.AWS_REGISTRY_URL }}/node-dria:${{ inputs.tag }}
          cache-from: type=registry,ref=${{ vars.AWS_REGISTRY_URL }}/node-dria:cache
          cache-to: type=registry,ref=${{ vars.AWS_REGISTRY_URL }}/node-dria:cache,compression=zstd,mode=max
