name: tests

on:
  push:
    branches:
      - master
    paths:
      # Source files in each member
      - "compute/src/**"
      - "p2p/src/**"
      - "utils/src/**"
      - "executor/src/**"
      # Cargo in each member
      - "compute/Cargo.toml"
      - "p2p/Cargo.toml"
      - "utils/Cargo.toml"
      - "executor/Cargo.toml"
      # root-level Cargo
      - "Cargo.toml"
      # workflow itself
      - ".github/workflows/tests.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: cargo test --workspace

      - name: Run linter
        run: cargo clippy --workspace
